services:
  frontend:
    build:
      context: ./frontend_reservation_optimizer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend_reservation_optimizer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"

  mongo:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 

volumes:
  mongo_data: