services:
  frontend:
    build:
      context: ./frontend_reservation_optimizer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - reservation_net

  backend:
    build:
      context: ./backend_reservation_optimizer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    networks:
      - reservation_net
  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - reservation_net
  mongo:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - reservation_net
      
volumes:
  mongo_data:

networks:
  reservation_net: